from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.chromium.launch(headless=True)
    page = browser.new_page()
    page.goto('https://www.amazon.in/s?k=iphone+17', wait_until='domcontentloaded')
    page.wait_for_selector('[data-component-type="s-search-result"] h2 a', timeout=30000)
    first_link_locator = page.locator('[data-component-type="s-search-result"] h2 a').first
    print('first link count', first_link_locator.count())
    first_link = first_link_locator.get_attribute('href')
    print('first link href', first_link)
    first_link_locator.click()
    page.wait_for_load_state('domcontentloaded', timeout=30000)
    print('product page url', page.url)
    print('product title', page.title())
    add_button = page.locator('input#add-to-cart-button, button#add-to-cart-button, button[name="submit.addToCart"]')
    print('add button count', add_button.count(), 'visible', add_button.is_visible())
    if add_button.is_visible():
        add_button.click()
        page.wait_for_timeout(10000)
        print('after click url', page.url)
        print('cart count', page.locator('#nav-cart-count').text_content())
        print('overlay added count', page.locator('text=Added to Cart').count())
        print('overlay any add count', page.locator('text=Add to Cart').count())
        print('overlay attach count', page.locator('div[id*="attach"]').count())
        print('page body contains add to cart text', 'Added to Cart' in page.content())
    browser.close()
